### ISSUE TITLE
Hey is this dead?

### ISSUE THREAD

**Issue by crabdancing** [CottonMC/FabricStarter#3]
I'd be willing to help maintain it. I've been doing more and more modding stuff lately :)

Let me know @Boundarybreaker!

**Comment by LemmaEOF** [comment]
Oh right, yeah. Lemme push a change to it then I can add you as a manager on the repo.

**Comment by LemmaEOF** [comment]
invite sent

**Comment by crabdancing** [comment]
Hmm I don't see it. :/

**Comment by LemmaEOF** [comment]
https://github.com/cottonmc/fabricstarter/invites

**Comment by crabdancing** [comment]
404s :S

**Comment by LemmaEOF** [comment]
wrote it wrong, https://github.com/cottonmc/fabricstarter/invitations

**Comment by crabdancing** [comment]
Cool, thx :)
